### PR TITLE
updated code examples to match provided wiring diagram

### PR DESCRIPTION
**Pull request by omnilord**
- The diagrm at https://github.com/bridystone/SevSegShift/blob/ShiftRegister/examples/SevSegShift_Counter/SevSegShift.png shows pins 11, 12, and 13 on the Arduino, but examples incorrectly coded to 10, 11, and 12 in reverse order.

### CODE REVIEW

**Comment by bridystone** [comment]
haha - good catch.

Have you tested with PIN 13?
I remember having problems with this default PIN, because it was used by several other connection (USB message LED, etc)

edit:
maybe the wiring diagram should rather be updated...

**Comment by omnilord** [comment]
I have an UNO wired up to match the diagram right now, and when my NANOs came in, I wired them up the same to test, so that's two different types of boards that work with Pin 13 no problems.

**Comment by bridystone** [comment]
That's good news - thanks for your efforts!
One final question:
Have you enabled the Serial-Monitor and put some debug messages to the Serial Monitor?
Serial.begin in the setup() and Serial.print("something") in the loop?

**Comment by omnilord** [comment]
Running a little late on getting back to you on this, but:

> That's good news - thanks for your efforts!
> One final question:
> Have you enabled the Serial-Monitor and put some debug messages to the Serial Monitor?
> Serial.begin in the setup() and Serial.print("something") in the loop?

Yes, none of my projects have been deployed yet, so they all have pretty thorough serial debugging throughout the sketches.

**Pull request merged**
